# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c07829afc23d65d5885f6ad7f34d7488cce53e8c46ad94b6aa65e7e654384f6ede7af5d33224d2de8a9ba9c8873f85f402affb9a50990a56d423b29094466f9d

test:
  secret_key_base: e757ea076c2d9f8dc3d467f4a8865001f24d232b566e259520d1a55f5b38d4184ae43ddaf05c5b2317baf441d49c81699e1e4817e3878ed83a4ed7c459c778de

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
